[package]
name = "putlebot-cli"
version = "0.1.0"
authors = ["Ole Martin Gjersvik <olgj@equinor.com>"]
edition = "2018"

[dependencies]
putlebot-server = { path = "../putlebot-server" }
clap = "2.33.0"